name = "QuantumDynamicsGWP"
uuid = "45bfa6d7-af3e-44f0-b20d-5825f4b1c6c2"
authors = ["Amartya Bose <amartya.bose@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
LinearAlgebra = "1.11.0"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
